# Impeller Flow Simulator Configuration

# ===========================================
# Default Impeller Parameters
# ===========================================
default_impeller:
  num_blades: 6
  outer_diameter: 0.3
  inner_diameter: 0.1
  blade_angle_inlet: 30
  blade_angle_outlet: 60
  blade_height: 0.05
  rotational_speed: 1750

# ===========================================
# Parameter Bounds for Optimization
# ===========================================
parameter_bounds:
  num_blades: [3, 12]
  blade_angle_inlet: [10, 60]
  blade_angle_outlet: [20, 70]
  rotational_speed: [500, 3000]

# ===========================================
# Parameter Adjustment Rules
# ===========================================
adjustment_rules:
  efficiency_threshold: 0.75
  angle_adjustment_step: 2.0
  speed_adjustment_factor: 1.1

# ===========================================
# Performance Targets
# ===========================================
performance_targets:
  min_efficiency: 0.70
  max_flow_error: 5.0
  max_head_error: 5.0

# ===========================================
# Global Optimization Settings
# ===========================================
optimization_settings:
  convergence_threshold: 5.0  # Increased from 1.0 to be more realistic
  save_results_dir: "results"
  log_level: "INFO"
  log_file: "optimization.log"

# ===========================================
# Test Cases
# ===========================================
test_cases:
  - name: "Very Low Flow Rate"
    flow_rates: [0.05]
    max_iterations: 100

  - name: "Low-Medium Flow Rate"
    flow_rates: [0.0605, 0.071, 0.0815]
    max_iterations: 100

  - name: "Medium Flow Rate"
    flow_rates: [0.092, 0.1025, 0.113]
    max_iterations: 100

  - name: "Medium-High Flow Rate"
    flow_rates: [0.1235, 0.134, 0.1445]
    max_iterations: 100

  - name: "High Flow Rate"
    flow_rates: [0.15]
    max_iterations: 100

  - name: "Full Range Test"
    flow_rates: [0.05, 0.0605, 0.071, 0.0815, 0.092, 0.1025, 0.113, 0.1235, 0.134, 0.1445, 0.15]
    max_iterations: 150